/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Streets */
        get: operations["list_streets_api_streets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Addresses */
        get: operations["list_addresses_api_addresses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match */
        get: operations["match_api_match_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/v2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Structured Match */
        get: operations["structured_match_api_match_v2_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Institutions */
        get: operations["list_institutions_api_institutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions/{institution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Institution */
        get: operations["get_institution_api_institutions__institution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressOut */
        AddressOut: {
            /** Id */
            id: number;
            /** Street Id */
            street_id: number;
            /** Number Int */
            number_int: number;
            /** Number Suffix */
            number_suffix: string | null;
            /** Entrance */
            entrance: string | null;
        };
        /** CoverageGroup */
        CoverageGroup: {
            street: components["schemas"]["StreetSummary"];
            /** Addresses */
            addresses: components["schemas"]["InstitutionAddress"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstitutionAddress */
        InstitutionAddress: {
            /** Id */
            id: number;
            /** Number Int */
            number_int: number;
            /** Number Suffix */
            number_suffix: string | null;
            /** Entrance */
            entrance: string | null;
        };
        /** InstitutionDetail */
        InstitutionDetail: {
            /** Id */
            id: number;
            /** External Id */
            external_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "nursery" | "kindergarten" | "preschool";
            /** Source Url */
            source_url: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Coverage */
            coverage: components["schemas"]["CoverageGroup"][];
        };
        /** InstitutionListItem */
        InstitutionListItem: {
            /** Id */
            id: number;
            /** External Id */
            external_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "nursery" | "kindergarten" | "preschool";
            /** Source Url */
            source_url: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /** MatchAddressContext */
        MatchAddressContext: {
            /** Id */
            id: number;
            /** District Code */
            district_code: ("01" | "02" | "03" | "04" | "05") | null;
            settlement: components["schemas"]["MatchSettlementContext"] | null;
        };
        /** MatchResult */
        MatchResult: {
            /** Id */
            id: number;
            /** External Id */
            external_id: string;
            /** Name */
            name: string;
            /**
             * Institution Kind
             * @enum {string}
             */
            institution_kind: "nursery" | "kindergarten" | "preschool";
            /**
             * Reception Kind
             * @enum {string}
             */
            reception_kind: "nursery" | "kindergarten" | "preschool";
            /**
             * Offering
             * @enum {string}
             */
            offering: "standard" | "infant_group";
            /** Source Url */
            source_url: string;
            /**
             * Match Basis
             * @enum {string}
             */
            match_basis: "address" | "district";
            /** Has Infant Group */
            has_infant_group: boolean;
        };
        /** MatchSettlementContext */
        MatchSettlementContext: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Locality Type
             * @enum {string}
             */
            locality_type: "city" | "village";
        };
        /** StreetOut */
        StreetOut: {
            /** Id */
            id: number;
            /** City */
            city: string;
            /** Raw Name */
            raw_name: string;
            /** Street Part */
            street_part: string;
            /** Type Marker */
            type_marker: string | null;
        };
        /** StreetSummary */
        StreetSummary: {
            /** Id */
            id: number;
            /** City */
            city: string;
            /** Raw Name */
            raw_name: string;
            /** Street Part */
            street_part: string;
            /** Type Marker */
            type_marker: string | null;
        };
        /** StructuredMatchResponse */
        StructuredMatchResponse: {
            address: components["schemas"]["MatchAddressContext"];
            /** Results */
            results: components["schemas"]["MatchResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_streets_api_streets_get: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_addresses_api_addresses_get: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_api_match_get: {
        parameters: {
            query: {
                /** @description addresses.id */
                address_id: number;
                /** @description Filter by institution kind */
                kind?: ("nursery" | "kindergarten" | "preschool") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structured_match_api_match_v2_get: {
        parameters: {
            query: {
                /** @description addresses.id */
                address_id: number;
                /** @description Filter by institution kind */
                kind?: ("nursery" | "kindergarten" | "preschool") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_institutions_api_institutions_get: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_institution_api_institutions__institution_id__get: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string | null;
            };
            path: {
                /** @description institutions.id */
                institution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
